pluginManagement {
    includeBuild('../../build-logic')

    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
}

rootProject.name = 'customer-service'
includeBuild '../../istad-common'

include 'customer-service-main'
include 'customer-service-domain:customer-domain-core'
include 'customer-service-domain:customer-application-service'
include 'customer-service-restapi'
include 'customer-service-persistence'
include 'customer-service-message'

project(':customer-service-domain:customer-application-service').projectDir =
        file('customer-service-domain/customer-application-service')
