pluginManagement {
    includeBuild('../build-logic')

    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
}
rootProject.name = 'microservices'
includeBuild '../istad-common'
include 'business-service'
include 'customer-service'
include 'customer-service:customer-service-domain'
include 'customer-service:customer-service-domain:customer-domain-core'
include 'customer-service:customer-service-domain:customer-application-service'

